# https://taskfile.dev

version: '3'

tasks:
  deploy:
    desc: Only Update Lambda Auth code
    vars:
      zip: ../dist/hello.zip
      lambda: bmi
    cmds:
      - zip -r -dd -q {{.zip}} .
      - aws lambda update-function-code --function-name  {{.lambda}} --zip-file fileb://{{.zip}}
